### ISSUE TITLE
View (MainMenu) 구현

### ISSUE THREAD

**Issue by sanghyeonJwa** [ssg-240304-java2/JD-3355datespot#2]
### ✔TODO
- [ ] 메인화면 플로우 제작
- [x] 메인화면 프린트 View 클래스 제작
- [x] 메인화면 구현 및 정리
- [ ] 메인화면 상시 노출 최신 게시글 구현

**Comment by Gyunorld** [comment]
MainMenu에서 상시 노출 최신 장소 구현
